var wxCodes = { 
  200:{description:"thunderstorm with light rain",id:"rain"},
  201:{description:"thunderstorm with rain",id:"rain"},
  202:{description:"thunderstorm with heavy rain",id:"rain"},
  210:{description:"light thunderstorm",id:"rain"},
  211:{description:"thunderstorm",id:"rain"},
  212:{description:"heavy thunderstorm",id:"rain"},
  221:{description:"ragged thunderstorm",id:"rain"},
  230:{description:"thunderstorm with light drizzle",id:"rain"},
  231:{description:"thunderstorm with drizzle",id:"rain"},
  232:{description:"thunderstorm with heavy drizzle",id:"rain"},
  300:{description:"light intensity drizzle",id:"rain"},
  301:{description:"drizzle",id:"rain"},
  302:{description:"heavy intensity drizzle",id:"rain"},
  310:{description:"light intensity drizzle rain",id:"rain"},
  311:{description:"drizzle rain",id:"rain"},
  312:{description:"heavy intensity drizzle rain",id:"rain"},
  313:{description:"shower rain and drizzle",id:"rain"},
  314:{description:"heavy shower rain and drizzle",id:"rain"},
  321:{description:"shower drizzle",id:"rain"},
  500:{description:"light rain",id:"rain"},
  501:{description:"moderate rain",id:"rain"},
  502:{description:"heavy intensity rain",id:"rain"},
  503:{description:"very heavy rain",id:"rain"},
  504:{description:"extreme rain",id:"rain"},
  511:{description:"freezing rain",id:"rain"},
  520:{description:"light intensity shower rain",id:"rain"},
  521:{description:"shower rain",id:"rain"},
  522:{description:"heavy intensity shower rain",id:"rain"},
  531:{description:"ragged shower rain",id:"rain"},
  600:{description:"light snow",id:"normal"},
  601:{description:"snow",id:"normal"},
  602:{description:"heavy snow",id:"normal"},
  611:{description:"sleet",id:"normal"},
  612:{description:"shower sleet",id:"normal"},
  615:{description:"light rain and snow",id:"normal"},
  616:{description:"rain and snow",id:"normal"},
  620:{description:"light shower snow",id:"normal"},
  621:{description:"shower snow",id:"normal"},
  622:{description:"heavy shower snow",id:"normal"},
  701:{description:"mist",id:"normal"},
  711:{description:"smoke",id:"normal"},
  721:{description:"haze",id:"normal"},
  731:{description:"sand, dust whirls",id:"normal"},
  741:{description:"fog",id:"normal"},
  751:{description:"sand",id:"normal"},
  761:{description:"dust",id:"normal"},
  762:{description:"volcanic ash",id:"normal"},
  771:{description:"squalls",id:"normal"},
  781:{description:"tornado",id:"normal"},
  800:{description:"clear sky",id:"sun"},
  801:{description:"few clouds",id:"sun"},
  802:{description:"scattered clouds",id:"sun"},
  803:{description:"broken clouds",id:"normal"},
  804:{description:"overcast clouds",id:"normal"},
  900:{description:"tornado",id:"rain"},
  901:{description:"tropical storm",id:"rain"},
  902:{description:"hurricane",id:"rain"},
  903:{description:"cold",id:"normal"},
  904:{description:"hot",id:"normal"},
  905:{description:"windy",id:"wind"},
  906:{description:"hail",id:"rain"},
  951:{description:"calm",id:"normal"},
  952:{description:"light breeze",id:"normal"},
  953:{description:"gentle breeze",id:"normal"},
  954:{description:"moderate breeze",id:"wind"},
  955:{description:"fresh breeze",id:"wind"},
  956:{description:"strong breeze",id:"wind"},
  957:{description:"high wind, near gale",id:"wind"},
  958:{description:"gale",id:"wind"},
  959:{description:"severe gale",id:"wind"},
  960:{description:"storm",id:"wind"},
  961:{description:"violent storm",id:"rain"},
  962:{description:"hurricane",id:"rain"}
};


